### ISSUE TITLE
Macro Camping and View Kingdom typeerror in console

### ISSUE THREAD

**Issue by nedroj12** [BernhardPosselt/pf2e-kingmaker-tools#29]
Thank you for your work. I am new to this and am having trouble.

**For camping macro I see:**
foundry.js:753 TypeError: An error occurred while rendering _ 208. Cannot read properties of undefined (reading 'currentRegion')
[Detected 1 package: pf2e-kingmaker-tools]
    at _.getData (sheet.ts:114:36)
    at async _._render (foundry.js:5734:18)
    at async _._render (foundry.js:6452:5)
**For View Kingdom I see:**
  foundry.js:753 TypeError: An error occurred while rendering M 209. Cannot read properties of undefined (reading 'size')
[Detected 4 packages: pf2e-kingmaker-tools, system:pf2e, monks-active-tiles, lib-wrapper]
    at M.getData (sheet.ts:124:50)
    at M._render (foundry.js:5734:29)
    at M._render (foundry.js:6452:17)
    at M.render (foundry.js:5691:10)
    at e (sheet.ts:1011:50)
    at Macro.eval (eval at #executeScript (foundry.js:22777:16), <anonymous>:4:32)
    at #executeScript (foundry.js:22781:17)
    at Macro.execute (foundry.js:22729:35)
    at Macro.execute (pf2e.mjs:37:23)
    at _HotbarPF2e2._onClickMacro (foundry.js:78356:20)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at _HotbarPF2e2.clickMacro (monks-active-tiles.js:1802:24)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Hotbar.prototype._onClickMacro#0 (libWrapper-wrapper.js:189:20)
    at HTMLLIElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by BernhardPosselt** [comment]
Can you describe exactly what you've done?

**Comment by nedroj12** [comment]
I'm not sure. I just created a fresh world with all the same activated modules, and it works. I'm going to go forward with this fresh world since I'm still in the prep stage for the game. If I figure out how I broke it I will update.

**Comment by BernhardPosselt** [comment]
You can delete the "Kingdom Sheet" and "Camping Sheet" actors and re-run the macros. Should work unless there's interference from other modules.
